kind: Service
apiVersion: v1
metadata:
  name: kt-rumble
  labels:
    app: kt-rumble
spec:
  type: NodePort
  selector:
    app: kt-rumble
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kt-rumble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kt-rumble
  template:
    metadata:
      labels:
        app: kt-rumble
        version: v1
    spec:
      containers:
      - name: kt-rumble
        image: chessequality/kt-rumble
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
